---
Gemfile:
  optional:
    ':test':
      - gem: 'toml'
spec/spec_helper_acceptance.rb:
  unmanaged: false
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_types
    - parameter_documentation
